### ISSUE TITLE
Vite apps server start not refreshing the playground/problem/solution panels

### ISSUE THREAD

**Issue by simonswiss** [epicweb-dev/pixel-perfect-tailwind#1]
For all exercises, clicking on "Star app" correctly starts the Vite dev server on the `process.env.PORT`, but the starting app party animation keeps going forever. I have to refresh the app to see the running app. 

No errors in the console, it just doesn’t update the app UI panel.

Is this because I am using a Vite app and not using the remix iframe-sync thing?

## Steps to reproduce

1. Run the workshop app locally
2. Start the app in any of the exercises
3. Check the terminal to see the app is running correctly
4. "Starting" animation hangs forever
5. Refresh page and app is running

**Comment by kentcdodds** [comment]
I pushed and released a fix. Because your workshop doesn't involve routing you shouldn't have to worry about the iframe-sync thing :)

Just update your version of `@kentcdodds/workshop-app` and it should start working :)

**Comment by kentcdodds** [comment]
Actually, it's not quite out yet. I'm going to just push the fix so you can get the latest with `npx kcdshop update`. Standby...

**Comment by kentcdodds** [comment]
I fixed a bunch of stuff related to linting and formatting. Unfortunately the auto-refresh stuff isn't working for some reason. Still looking into that.

**Comment by kentcdodds** [comment]
Fixed! You can run:

```
npx kcdshop update
```

Or just git pull and npm install :)
